(function(){
 'use strict';
 const A=CMHS_STUDIO,E=CMHS_V2_ENGINE,{NetworkDocument}=CMHS;
 const {el,button}=A;let clipboard=A.store.get('clipboard',null),lastBatch=null;
 const close=()=>document.getElementById('modal').close();
 const note=(body,text)=>body.append(el('p','v2-note',text));
 function check(body,label,checked=false){const row=el('label','v2-check'),input=el('input');input.type='checkbox';input.checked=checked;row.append(input,document.createTextNode(label));body.append(row);return input;}
 function select(body,label,items){const row=el('label','field'),s=el('select');row.append(el('span','',label),s);items.forEach(([value,text])=>{const o=el('option','',text);o.value=value;s.append(o);});body.append(row);return s;}
 function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 function currentDocuments(all){return A.networks.filter(n=>all?A.drafts.has(n.id):n.id===A.activeId).map(n=>({id:n.id,filename:n.filename||n.id,xml:n.id===A.activeId?A.model.toXML():n.xml}));}
 function copy(){try{clipboard=E.fragment(A.model,A.selectedNames());A.store.put('clipboard',clipboard);A.toast(`Copied ${clipboard.nodes.length} elements and ${clipboard.edges.length} internal connections.`);updateToolbar();}catch(e){A.toast(e.message,true);}}
 function pasteDialog(){if(!clipboard){A.toast('Select elements and copy them first.',true);return;}const body=el('div');note(body,`From ${clipboard.network}: ${clipboard.nodes.length} elements, ${clipboard.edges.length} internal connections. ${clipboard.externalLinks} external connections are excluded. Names are made unique; existing destination variables keep their values.`);const producer=clipboard.nodes.some(xml=>CMHS.parseXML(xml).documentElement.tagName==='producer'),exists=A.model.nodes.some(n=>n.tagName==='producer');const replace=producer&&exists?check(body,'Replace the existing source (retaining its outgoing connections)'):null;A.modal('Paste network pieces',body,[{text:'Paste',run:()=>{const p=A.centerPosition(),result=A.perform(()=>E.paste(A.model,clipboard,p.x,p.y,{replaceProducer:!!replace?.checked}));if(result?.ok){close();A.setSelectedNames(result.result.names);A.fit();A.toast(result.result.conflicts.length?'Pasted. Kept destination variables: '+result.result.conflicts.join(', '):'Network pieces pasted.');}}}]);}
 function arrange(){const body=el('div');note(body,'Arrange follows connections from left to right, with processors above outputs. Shift-click elements to select a group for alignment.');const selected=check(body,'Arrange selected elements only',A.selectedNames().length>1);const grid=el('div','v2-actions');[['left','Align left'],['center-x','Center horizontally'],['right','Align right'],['top','Align top'],['center-y','Center vertically'],['bottom','Align bottom'],['space-x','Distribute horizontally'],['space-y','Distribute vertically']].forEach(([mode,label])=>grid.append(button(label,()=>{const r=A.perform(()=>E.align(A.model,A.selectedNames(),mode));if(r?.ok)close();})));body.append(grid);A.modal('Arrange & align',body,[{text:'Arrange graph',run:()=>{if(selected.checked&&!A.selectedNames().length)throw Error('Select elements first.');A.perform(()=>E.layout(A.model,selected.checked?A.selectedNames():null));close();A.fit();}}]);}
 function logs(){const body=el('div');note(body,'Attach a FileWriter to each producer and processor output. Existing FileWriter connections are skipped. Consumers have no output port. Log paths use %INTERFACEDIR%\\%NETWORKNAME%\\Log.');const arrangeAfter=check(body,'Arrange graph after adding writers',true);A.modal('Add output filewriters',body,[{text:'Add filewriters',run:()=>{const template=A.catalog.instances.find(i=>i.role==='consumer'&&i.typename==='FileWriter');if(!template)throw Error('No FileWriter template in the library.');const r=A.perform(()=>{const result=E.addLogs(A.model,template.xml);if(arrangeAfter.checked)E.layout(A.model);return result;});if(r?.ok){close();A.fit();A.toast(`${r.result.added} filewriters added; ${r.result.skipped} existing log connections skipped.`);}}}]);}
 function dbLogs(){const body=el('div');note(body,'Attach a CMHSDBLogWriterConsumer to each producer and processor. Existing DB logwriters are skipped. The selected library example supplies Environment, MessageFormat and EnableLogging; each new Identifier is based on the source element. Referenced network variables are copied when missing; existing values are retained.');const examples=A.catalog.instances.filter(i=>i.role==='consumer'&&i.typename==='CMHSDBLogWriterConsumer');const example=select(body,'DB logwriter configuration',examples.map(i=>[i.id,`${i.networkId} / ${i.name}`]));const arrangeAfter=check(body,'Arrange graph after adding DB logwriters',true);A.modal('Add database logwriters',body,[{text:'Add DB logwriters',primary:true,run:()=>{const template=examples.find(i=>i.id===example.value);if(!template)throw Error('No CMHSDBLogWriterConsumer template in the library.');const r=A.perform(()=>{const origin=A.catalog.networks.find(n=>n.id===template.networkId),variables=origin?E.fragment(new NetworkDocument(origin.xml,origin.id),[template.name]).variables:[];const result=E.addDBLogs(A.model,template.xml,variables);if(arrangeAfter.checked)E.layout(A.model);return result;});if(r?.ok){close();A.fit();A.toast(`${r.result.added} DB logwriters added; ${r.result.skipped} skipped.${r.result.conflicts.length?" Kept destination variables: "+r.result.conflicts.join(", "):""}`);}}}]);}
 let menu=null,contextTarget=null;
 function hideMenu(){if(menu){menu.remove();menu=null;}contextTarget=null;}
 function duplicateSelection(){const names=A.selectedNames();if(names.some(n=>A.model.node(n)?.tagName==='producer')){A.toast('A network can have only one producer; select processors or consumers to duplicate.',true);return;}const p=E.fragment(A.model,names),nodes=names.map(n=>A.model.node(n)),x=Math.min(...nodes.map(n=>A.model.position(n).x))+30,y=Math.min(...nodes.map(n=>A.model.position(n).y))+65;const r=A.perform(()=>E.paste(A.model,p,x,y));if(r?.ok)A.setSelectedNames(r.result.names);}
 function contextMenu(event,name){hideMenu();if(!A.selectedNames().includes(name))A.setSelectedNames([name]);contextTarget=name;menu=el('div','node-context-menu');menu.setAttribute('role','menu');menu.setAttribute('aria-label','Element actions');const items=[['Copy',copy],['Duplicate',duplicateSelection],['Delete',A.deleteSelection]];items.forEach(([label,action])=>{const b=button(label,()=>{hideMenu();try{action();}catch(e){A.toast(e.message,true);}});b.setAttribute('role','menuitem');if(label==='Duplicate')b.disabled=A.selectedNames().some(n=>A.model.node(n)?.tagName==='producer');menu.append(b);});document.body.append(menu);const r=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(event.clientX,innerWidth-r.width-8))+'px';menu.style.top=Math.max(8,Math.min(event.clientY,innerHeight-r.height-8))+'px';menu.querySelector('button').focus();}
 document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target))hideMenu();},true);
 document.addEventListener('keydown',e=>{if(!menu)return;const buttons=[...menu.querySelectorAll('button:not(:disabled)')];if(e.key==='Escape'){const name=contextTarget;hideMenu();[...document.querySelectorAll('[data-node]')].find(n=>n.getAttribute('data-node')===name)?.focus();e.preventDefault();e.stopImmediatePropagation();}else if(['ArrowDown','ArrowUp','Tab'].includes(e.key)){e.preventDefault();const delta=e.key==='ArrowUp'||(e.key==='Tab'&&e.shiftKey)?-1:1;buttons[(buttons.indexOf(document.activeElement)+delta+buttons.length)%buttons.length].focus();e.stopImmediatePropagation();}},true);
 window.addEventListener('resize',hideMenu);window.addEventListener('blur',hideMenu);
 function replaceDialog(){const body=el('div'),defs=A.catalog.definitions;const source=select(body,'Replace element type',defs.map(d=>[d.id,`${d.role} · ${d.typename} · ${d.module}`]));const selected=A.model.node(A.selectedNames()[0]);if(selected){const d=defs.find(d=>d.role===selected.tagName&&d.typename===selected.getAttribute('typename')&&d.module===selected.getAttribute('module'));if(d)source.value=d.id;}const target=select(body,'Replacement configuration',[]),scope=select(body,'Scope',[['current','Current network'],['all','All workspace networks']]),keep=check(body,'Keep matching parameter values and attributes',true),preview=el('p','v2-note');body.append(preview);
 const refresh=()=>{const match=defs.find(d=>d.id===source.value);preview.textContent=A.networks.filter(n=>scope.value==='all'||n.id===A.activeId).reduce((total,n)=>total+new NetworkDocument(n.id===A.activeId?A.model.toXML():n.xml,n.id).nodes.filter(v=>v.tagName===match.role&&v.getAttribute('typename')===match.typename&&v.getAttribute('module')===match.module).length,0)+' matching elements. Connections, names and positions will be preserved.';};
 const choices=()=>{const match=defs.find(d=>d.id===source.value);target.replaceChildren();A.catalog.instances.filter(i=>i.role===match.role).forEach(i=>{const o=el('option','',`${i.typename} · ${i.networkId} / ${i.name}`);o.value=i.id;target.append(o);});refresh();};source.onchange=choices;scope.onchange=refresh;choices();
 A.modal('Replace elements',body,[{text:'Apply replacement',run:()=>{const match=defs.find(d=>d.id===source.value),template=A.catalog.instances.find(i=>i.id===target.value),before=[],after=[];let count=0;A.networks.filter(n=>scope.value==='all'||n.id===A.activeId).forEach(n=>{const xml=n.id===A.activeId?A.model.toXML():n.xml,m=new NetworkDocument(xml,n.id),changed=E.replace(m,match,template.xml,keep.checked);if(changed){count+=changed;before.push({id:n.id,xml});after.push({id:n.id,xml:m.toXML()});}});if(!count)throw Error('No matching elements.');A.commitNetworks(after);lastBatch={before,after};close();updateToolbar();A.toast(`Replaced ${count} elements in ${after.length} networks.`);}}]);}
 function undoBatch(){try{if(!lastBatch)return;for(const item of lastBatch.after){const actual=item.id===A.activeId?A.model.toXML():A.networks.find(n=>n.id===item.id)?.xml;if(actual!==item.xml)throw Error('Affected networks changed after replacement. Undo those edits before undoing the bulk replacement.');}A.commitNetworks(lastBatch.before);lastBatch=null;updateToolbar();A.toast('Bulk replacement undone.');}catch(e){A.toast(e.message,true);}}
 function saveDialog(all=false){
  const docs=currentDocuments(all);if(!docs.length){A.toast('No modified networks to export.');return;}
  const body=el('div'),processors=[],decorators=[],models=new Map();
  docs.forEach(d=>{const m=new NetworkDocument(d.xml,d.filename);models.set(d.id,m);m.nodes.forEach(n=>{const item={id:d.id,name:n.getAttribute('name'),network:m.name};if(n.getAttribute('typename')==='XSLProcessor')processors.push(item);if(/XMLDecorator/i.test(n.getAttribute('typename')))decorators.push(item);});});
  note(body,`Export ${docs.length} network${docs.length===1?'':'s'}. Generated files are downloaded together in a ZIP; source files on disk are not overwritten.`);
  let createXSL=null,createCQMS=null;const chosen=[],queryFields=[];
  if(processors.length){
   createXSL=check(body,'Create starter XSL files and update selected processor filenames');
   note(body,'Uses templates/xsl_template.xsl. Review the starter logic before deployment. Existing XSL logic is not copied.');
   const list=el('div','v2-file-list');
   processors.forEach(p=>{const card=el('div','v2-query-card'),input=check(card,`${p.network} / ${p.name}`,true),queryArea=el('div');queryArea.hidden=true;const choices=decorators.filter(d=>d.id===p.id),querySource=select(queryArea,'Queries for this XSL',[['','No CQMS queries'],...choices.map(d=>[d.name,d.name])]);const downstream=E.downstreamDecorators(models.get(p.id),p.name);if(downstream.length===1)querySource.value=downstream[0];card.append(queryArea);list.append(card);chosen.push({...p,input,querySource,queryArea});});
   body.append(list);list.hidden=true;createXSL.onchange=()=>list.hidden=!createXSL.checked;
  }
  if(decorators.length){
   createCQMS=check(body,'Create CQMS query files');const area=el('div');area.hidden=true;
   note(area,'Define queries separately for each network and XMLDecorator. Enter one query name per line, or CSV with queryname,parameters,sql,comment columns.');
   decorators.forEach(d=>{const card=el('section','v2-query-card');card.append(el('strong','',d.network+' / '+d.name));const input=el('textarea','code-area');input.rows=3;input.placeholder='queryname\nGetExample';input.setAttribute('aria-label',`Queries for ${d.network} / ${d.name}`);card.append(input);area.append(card);queryFields.push({...d,input});});
   const csvLabel=el('label','field');csvLabel.append(el('span','','Import a mapping CSV (network,decorator,queryname)'));const file=el('input');file.type='file';file.accept='.csv,text/csv';csvLabel.append(file);area.append(csvLabel);
   file.onchange=async()=>{try{if(!file.files[0])return;const rows=E.queryRows(await file.files[0].text());E.validateQueryMappings(decorators.map(d=>({network:d.network,decorator:d.name})),rows);const quote=s=>'"'+String(s??'').replace(/"/g,'""')+'"';queryFields.forEach(d=>{const subset=rows.filter(r=>r.network===d.network&&r.decorator===d.name),headers=['queryname','parameters','sql','comment'].filter(h=>h==='queryname'||subset.some(r=>r[h]!==undefined));d.input.value=[headers.join(','),...subset.map(r=>headers.map(h=>quote(r[h])).join(','))].join('\n');});A.toast('Query mappings loaded.');}catch(e){A.toast(e.message,true);}finally{file.value='';}};
   body.append(area);createCQMS.onchange=()=>{area.hidden=!createCQMS.checked;chosen.forEach(p=>p.queryArea.hidden=!createCQMS.checked);};
   note(area,'Query paths: Custom/CMHS/<network>/<queryname>. Each selected XSL uses only the queries from its chosen decorator. Existing XSL files remain unchanged.');
  }
  const preview=el('pre','v2-preview');body.append(preview);
  const build=()=>{
   const xslNodes=Object.create(null),xslDecorators=Object.create(null),queryMappings=[];
   if(createXSL?.checked)chosen.filter(p=>p.input.checked).forEach(p=>{(xslNodes[p.id]??=[]).push(p.name);(xslDecorators[p.id]??=Object.create(null))[p.name]=p.querySource.value;});
   if(createXSL?.checked&&!Object.keys(xslNodes).length)throw Error('Select at least one XSL processor.');
   if(createCQMS?.checked)queryFields.forEach(d=>{if(!d.input.value.trim())throw Error(`Define queries for ${d.network} / ${d.name}.`);E.queryRows(d.input.value).forEach(row=>{if((row.network&&row.network!==d.network)||(row.decorator&&row.decorator!==d.name))throw Error(`Query mapping does not match ${d.network} / ${d.name}.`);queryMappings.push({...row,network:d.network,decorator:d.name});});});
   const result=E.bundle(docs,{xslNodes,xslDecorators,cqms:!!createCQMS?.checked,queryMappings,templates:CMHS_TEMPLATES});
   result.mappingPreview=queryMappings.map(q=>`${q.network} / ${q.decorator} → Custom/CMHS/${q.network}/${q.queryname}`).join('\n');return result;
  };
  A.modal('Save network & optional files',body,[{text:'Preview files',run:()=>{const result=build();preview.textContent=result.files.map(f=>f.name).join('\n')+(result.mappingPreview?'\n\nQuery mappings\n'+result.mappingPreview:'');}},{text:'Download',run:()=>{const result=build();if(result.files.length===1)download(result.files[0].name.split('/').pop(),result.files[0].text,'application/xml');else download(docs.length===1?E.safeName(new NetworkDocument(docs[0].xml).name)+'_bundle.zip':'cmhs_networks.zip',E.zip(result.files),'application/zip');const updates=result.updates.filter(u=>new NetworkDocument(docs.find(d=>d.id===u.id).xml).toXML()!==u.xml);if(updates.length)A.commitNetworks(updates);close();A.toast(`Downloaded ${result.files.length} files.`);}}]);
 }
 const toolbar=el('div','v2-toolbar'),count=el('span','v2-count');const copyButton=button('Copy',copy),pasteButton=button('Paste',pasteDialog),undoButton=button('Undo replacement',undoBatch);toolbar.append(copyButton,pasteButton,button('Arrange / Align',arrange),button('Add filewriters',logs),button('Add DB logwriters',dbLogs),button('Replace elements',replaceDialog),undoButton,button('Export all drafts',()=>saveDialog(true)),count);document.querySelector('.canvas-toolbar').after(toolbar);
 function updateToolbar(){copyButton.disabled=!A.selectedNames().length;pasteButton.disabled=!clipboard;undoButton.disabled=!lastBatch;count.textContent=A.selectedNames().length+' selected';}
 const canvas=document.getElementById('canvas');canvas.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-cmhs-template')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});canvas.addEventListener('drop',e=>{const raw=e.dataTransfer.getData('application/x-cmhs-template');if(!raw)return;e.preventDefault();e.stopPropagation();try{const t=JSON.parse(raw),p=A.canvasPosition(e.clientX,e.clientY),add=()=>{const r=A.perform(()=>A.model.add(t.xml,p.x,p.y,A.templateNetwork(t)));if(r?.ok)A.setSelectedNames([r.result]);};if(CMHS.parseXML(t.xml).documentElement.tagName==='producer'&&A.model.nodes.some(n=>n.tagName==='producer')){const body=el('div');note(body,'This replaces the current source and retains its existing connections.');A.modal('Replace network source?',body,[{text:'Replace source',run:()=>{add();close();}}]);}else add();}catch(error){A.toast(error.message,true);}});
 window.CMHS_V2={contextMenu,copy,pasteDialog,saveDialog,updateToolbar,renderMultiInspector(panel,names){panel.append(el('h2','',`${names.length} selected elements`));const section=A.section('Group actions');note(section,names.join(', '));section.append(button('Copy selection',copy),button('Arrange / Align',arrange),button('Delete selection',A.deleteSelection));panel.append(section);}};updateToolbar();
})();
