document.getElementById('run').onclick=()=>{
 const output=document.getElementById('results');output.textContent='';output.className='';let count=0;
 const check=(ok,text)=>{if(!ok)throw Error(text);count++;output.textContent+='PASS '+text+'\n';};
 try{
 const {NetworkDocument,parseXML,serialize}=CMHS,E=CMHS_V2_ENGINE,C=CMHS_CATALOG;
 const declaration='<?xml version="1.0" encoding="UTF-8"?>';
 [CMHS_TEMPLATES.xsl.replace(/^\s*<\?xml\s[^?]*\?>\s*/,''),CMHS.withXMLDeclaration(CMHS_TEMPLATES.xsl)].forEach(template=>{
  const xml=E.generateXSL('DeclarationTest',template,[]);check((xml.match(/<\?xml\s/g)||[]).length===1&&xml.startsWith(declaration),'XSL export has exactly one declaration with either template form');check(parseXML(xml).documentElement.localName==='stylesheet','Generated XSL parses after declaration normalization');
 });
 const queryXML=E.generateCQMS('DeclarationTest',[{network:'DeclarationTest',decorator:'D',queryname:'Q'}],CMHS.withXMLDeclaration(CMHS_TEMPLATES.cqms)).xml;
 check((queryXML.match(/<\?xml\s/g)||[]).length===1&&parseXML(queryXML).documentElement.tagName==='ComtecQueries','CQMS export also has one declaration');
 const cpmsXML=E.generateCPMS(['FirstNetwork','SecondNetwork'],CMHS_TEMPLATES.cpms),cpmsDoc=parseXML(cpmsXML),processConfigs=[...cpmsDoc.getElementsByTagName('processConfig')];
 check((cpmsXML.match(/<\?xml\s/g)||[]).length===1&&processConfigs.length===2&&processConfigs[0].getAttribute('code')==='cmhs_FirstNetwork'&&processConfigs[1].getAttribute('name')==='CMHS - SecondNetwork'&&processConfigs[1].getElementsByTagName('include-network')[0].textContent==='SecondNetwork','CPMS export contains one configured process per network');
 C.networks.forEach(n=>{const m=new NetworkDocument(n.xml,n.id),round=new NetworkDocument(m.toXML(),n.id);check(round.nodes.length===n.nodeCount&&round.edges.length===n.connectionCount&&!round.issues().some(i=>i.level==='error'),n.id+' XML roundtrip');});
 const positioned=new NetworkDocument(C.networks[0].xml,C.networks[0].id);positioned.nodes[0].setAttribute('x','-40');positioned.nodes[0].setAttribute('y','-30');const normalized=new NetworkDocument(positioned.toXML(),positioned.filename);check(normalized.nodes.every(n=>normalized.position(n).x>=CMHS.MIN_X&&normalized.position(n).y>=CMHS.MIN_Y),'Imported coordinates normalize to the positive native canvas');normalized.move(normalized.nodes[0].getAttribute('name'),-1,-1);check(normalized.position(normalized.nodes[0]).x===CMHS.MIN_X&&normalized.position(normalized.nodes[0]).y===CMHS.MIN_Y,'Element movement cannot create negative coordinates');
 const renamed=new NetworkDocument(C.networks.find(n=>n.nodeCount>2).xml),oldNetwork=renamed.name,oldNames=renamed.nodes.map(n=>n.getAttribute('name'));renamed.renameNetwork('RenamedNetwork');const renamedNames=renamed.nodes.map(n=>n.getAttribute('name'));check(renamed.name==='RenamedNetwork'&&new Set(renamedNames).size===renamedNames.length&&renamedNames.every((name,index)=>name!==oldNames[index]&&/_RenamedNetwork_\d+$/.test(name))&&renamed.edges.every(e=>renamed.node(e.getAttribute('producer'))&&renamed.node(e.getAttribute('consumer'))),'Network rename rebuilds element names with network and serial while preserving connections');
 const source=new NetworkDocument(C.networks.find(n=>n.xml.includes('XSLProcessor')&&n.xml.includes('XMLDecorator')).xml);
 const dest=new NetworkDocument(source.toXML());const names=source.nodes.filter(n=>n.tagName!=='producer').map(n=>n.getAttribute('name'));const piece=E.fragment(source,names),original=dest.nodes.length,result=E.paste(dest,piece,100,200);
 check(dest.nodes.length===original+names.length&&new Set(dest.nodes.map(n=>n.getAttribute('name'))).size===dest.nodes.length,'Paste makes names unique');check(result.links===piece.edges.length,'Paste preserves internal connections');
 const writer=C.instances.find(i=>i.typename==='FileWriter'&&i.role==='consumer');E.addLogs(dest,writer.xml);check(E.addLogs(dest,writer.xml).added===0,'Bulk filewriters are idempotent');check(!dest.issues().some(i=>i.level==='error'),'Pasted/logged graph connections valid');
 const db=C.instances.find(i=>i.typename==='CMHSDBLogWriterConsumer'),dbExpected=dest.nodes.filter(n=>n.tagName!=='consumer'&&!dest.edges.some(e=>e.getAttribute('producer')===n.getAttribute('name')&&dest.node(e.getAttribute('consumer'))?.getAttribute('typename')==='CMHSDBLogWriterConsumer')).length,dbAdded=E.addDBLogs(dest,db.xml);check(dbAdded.added===dbExpected,'DB logs attached to every source/processor');check(E.addDBLogs(dest,db.xml).added===0,'DB logwriters are idempotent');check(!dest.issues().some(i=>i.level==='error'),'DB logging preserves legal inputs and outputs');
 const bare=NetworkDocument.empty('Rules');const prod=C.instances.find(i=>i.role==='producer'),proc=C.instances.find(i=>i.role==='processor');const p=bare.add(prod.xml,0,0),a=bare.add(proc.xml,100,0),b=bare.add(proc.xml,100,100),out=bare.add(writer.xml,200,0);bare.connect(p,a);bare.connect(a,out);let caught=false;try{bare.connect(b,out);}catch{caught=true;}check(caught,'Second incoming connection blocked');caught=false;try{bare.connect(a,a);}catch{caught=true;}check(caught,'Self connection blocked');bare.remove(out);check(bare.issues().some(i=>i.level==='error'&&i.message.includes('output consumer')),'Output required at final validation');
 E.layout(dest);
E.align(dest,result.names,'left');check(result.names.every(n=>dest.position(dest.node(n)).x===dest.position(dest.node(result.names[0])).x),'Arrange and align');
 const replacement=C.instances.find(i=>i.role==='processor'),match=C.definitions.find(d=>d.id===replacement.definitionId);const beforeEdges=dest.edges.map(serialize).join('');E.replace(dest,match,replacement.xml,true);check(dest.edges.map(serialize).join('')===beforeEdges,'Replacement preserves connections');
 const rows=E.queryRows('queryname,parameters,sql,comment\nGetOne,contactid:string=42,"select @contactid, 1",First\nGetTwo,other:string=,"select @other",Second');const q=E.generateCQMS('Example',rows.map(r=>({...r,network:'Example',decorator:'Decorator'})),CMHS_TEMPLATES.cqms),qd=parseXML(q.xml);check(qd.getElementsByTagName('query').length===2&&qd.getElementsByTagName('query')[1].getAttribute('name')==='Custom/CMHS/Example/GetTwo','CQMS query paths');const x=E.generateXSL('Example',CMHS_TEMPLATES.xsl,q.queries),xd=parseXML(x);check(xd.getElementsByTagName('query').length===2&&xd.getElementsByTagName('query')[1].getAttribute('name')===qd.getElementsByTagName('query')[1].getAttribute('name'),'XSL and CQMS paths match');check(xd.getElementsByTagName('query')[1].getElementsByTagName('parameter')[0].getAttribute('name')==='other','XSL and CQMS parameters match');
 const generic=E.generateCQMS('Generic',E.queryRows('GetExample').map(r=>({...r,network:'Generic',decorator:'Decorator'})),CMHS_TEMPLATES.cqms);check(parseXML(generic.xml).getElementsByTagName('parameter')[0].getAttribute('name')==='id','Generic CQMS template uses id');check(!generic.xml.includes('Test_web/query1'),'CQMS SQL comment rebased');
 const sourceBefore=source.toXML();const processors=source.nodes.filter(n=>n.getAttribute('typename')==='XSLProcessor').map(n=>n.getAttribute('name'));const bundle=E.bundle([{id:'test',xml:source.toXML()}],{xslNodes:{test:processors},cqms:true,cpms:true,queryMappings:source.nodes.filter(n=>/XMLDecorator/i.test(n.getAttribute('typename'))).map((n,i)=>({network:source.name,decorator:n.getAttribute('name'),queryname:'GetOne'+i})),xslDecorators:{test:Object.fromEntries(processors.map(n=>[n,E.downstreamDecorators(source,n)[0]||'']))},templates:CMHS_TEMPLATES});check(bundle.files.some(f=>f.name===`networks/${source.name}.mhn`),'Network filename has no modified suffix');check(bundle.files.length===processors.length+3&&bundle.files.find(f=>f.name==='CPMS/cmhs-process-config.xml').text.includes(`<include-network>${source.name}</include-network>`),'Bundle includes network, XSLs, CQMS and consolidated CPMS');const updated=new NetworkDocument(bundle.updates[0].xml);check(processors.every(n=>updated.parameters(n).find(p=>p.getAttribute('name')==='filename').getAttribute('value').includes('%NETWORKNAME%')),'Export updates processor filenames');
 const from=NetworkDocument.empty('Origin'),to=NetworkDocument.empty('Destination');
 const originProcessor=from.add(proc.xml,0,0),originWriter=from.add(writer.xml,150,0,writer.networkId.replace(/\.mhn$/,''));from.connect(originProcessor,originWriter);
 const copied=E.paste(to,E.fragment(from,[originProcessor,originWriter]),10,10),copiedWriter=to.nodes.find(n=>n.getAttribute('typename')==='FileWriter');
 check(copiedWriter.getAttribute('name').includes('_Destination_')&&!copiedWriter.getAttribute('name').includes('_Origin_'),'Cross-network paste rebases filewriter name');check(to.edges[0].getAttribute('consumer')===copiedWriter.getAttribute('name'),'Pasted connection uses rebased name');
 const duplicate=to.duplicate(copiedWriter.getAttribute('name'));check(duplicate.replace(/_\d+$/,'')===copiedWriter.getAttribute('name').replace(/_\d+$/,''),'Duplicate increments existing counter');
 const queryNetwork=NetworkDocument.empty('QueryTest'),xslTemplate=C.instances.find(i=>i.typename==='XSLProcessor'),decoratorTemplate=C.instances.find(i=>/XMLDecorator/i.test(i.typename));
 const chain=[queryNetwork.add(prod.xml,0,0),queryNetwork.add(xslTemplate.xml,100,0),queryNetwork.add(decoratorTemplate.xml,200,0),queryNetwork.add(xslTemplate.xml,300,0),queryNetwork.add(decoratorTemplate.xml,400,0),queryNetwork.add(writer.xml,500,100,writer.networkId.replace(/\.mhn$/,''))];chain.slice(1).forEach((n,i)=>queryNetwork.connect(chain[i],n));
 const mappedBundle=E.bundle([{id:'mapped',xml:queryNetwork.toXML()}],{xslNodes:{mapped:[chain[1],chain[3]]},xslDecorators:{mapped:{[chain[1]]:chain[2],[chain[3]]:chain[4]}},cqms:true,queryMappings:[{network:'QueryTest',decorator:chain[2],queryname:'First'},{network:'QueryTest',decorator:chain[4],queryname:'Second'}],templates:CMHS_TEMPLATES});
 const sheets=mappedBundle.files.filter(f=>f.name.endsWith('.xsl')).map(f=>parseXML(f.text));check(sheets[0].getElementsByTagName('query').length===1&&sheets[0].getElementsByTagName('query')[0].getAttribute('name')==='Custom/CMHS/QueryTest/First','First XSL includes only first decorator query');check(sheets[1].getElementsByTagName('query').length===1&&sheets[1].getElementsByTagName('query')[0].getAttribute('name')==='Custom/CMHS/QueryTest/Second','Second XSL includes only second decorator query');
 check(parseXML(E.generateXSL('QueryTest',CMHS_TEMPLATES.xsl,[])).getElementsByTagName('query').length===0,'Unmapped XSL has no CQMS query placeholder');
 const secondNetwork=new NetworkDocument(queryNetwork.toXML());secondNetwork.variables.find(v=>v.getAttribute('name')==='NETWORKNAME').setAttribute('value','OtherNetwork');
 const mixed=E.bundle([{id:'first',xml:queryNetwork.toXML()},{id:'second',xml:secondNetwork.toXML()}],{cqms:true,queryMappings:[...chain.filter((_,i)=>i===2||i===4).map((name,i)=>({network:'QueryTest',decorator:name,queryname:'Original'+i})),...chain.filter((_,i)=>i===2||i===4).map((name,i)=>({network:'OtherNetwork',decorator:name,queryname:'Other'+i}))],templates:CMHS_TEMPLATES});
 check(!mixed.files.find(f=>f.name==='CQMS/QueryTest.xml').text.includes('OtherNetwork')&&!mixed.files.find(f=>f.name==='CQMS/OtherNetwork.xml').text.includes('Original0'),'Queries stay within their mapped network');
 check(source.toXML()===sourceBefore,'Bundle does not mutate source document');output.textContent+='\n'+count+' checks passed. Now review drag/drop, selection, popup controls and downloads in the portal.';
 }catch(e){output.className='fail';output.textContent+='FAIL '+e.stack;}
};
